; Revit Spatial Analyzer - Windows installer
;
; Built by tools/build-installer.ps1, which stages the assemblies and passes
; the version in. Running ISCC against this file directly will fail on the
; missing staging directory, which is deliberate: the staging step is what
; proves no Autodesk assembly is about to be redistributed.
;
; Two properties this installer is careful about, for the same reasons the
; development deploy script is:
;
;   * It never asks for administrator rights. Everything it writes lives under
;     the current user's profile. A Revit add-in does not need machine-wide
;     installation, and asking for elevation to write a manifest is a good way
;     to be refused by the person who has to approve it.
;
;   * It never carries Autodesk's assemblies. Revit loads RevitAPI.dll and
;     RevitAPIUI.dll from its own installation. Shipping copies would risk
;     binding the add-in against assemblies that disagree with the host, and
;     redistributing them is not ours to do.

#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

#ifndef Staging
  #define Staging "staging"
#endif

#define AppName        "Revit Spatial Analyzer"
#define AppPublisher   "Aplos"
#define RevitVersion   "2025"
#define AddinsDir      "{userappdata}\Autodesk\Revit\Addins\" + RevitVersion
#define ManifestName   "SpatialAnalyzer.addin"

[Setup]
AppId={{7C4F5E62-3A9D-4B18-9F31-2E6C8D40A7B5}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion} for Revit {#RevitVersion}
AppPublisher={#AppPublisher}
VersionInfoVersion={#AppVersion}

; Per-user throughout. No elevation is requested and none is needed.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={localappdata}\RevitSpatialAnalyzer\{#RevitVersion}
DisableDirPage=yes
DisableProgramGroupPage=yes
UsePreviousAppDir=yes

OutputDir=Output
OutputBaseFilename=RevitSpatialAnalyzer-{#AppVersion}-Revit{#RevitVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible

; Revit locks the add-in assemblies once it has loaded them. Letting the
; restart manager notice that is far kinder than failing halfway through with
; a file-in-use error.
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#Staging}\SpatialAnalyzer.Revit.dll";       DestDir: "{app}"; Flags: ignoreversion
Source: "{#Staging}\SpatialAnalyzer.Core.dll";        DestDir: "{app}"; Flags: ignoreversion
Source: "{#Staging}\SpatialAnalyzer.Revit.deps.json"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#Staging}\{#ManifestName}.in";              DestDir: "{app}"; Flags: ignoreversion

[UninstallDelete]
; The manifest is written at install time into Revit's own Addins folder, which
; is outside {app}, so it has to be named for removal explicitly. Leaving it
; behind would point Revit at an assembly that no longer exists, and Revit
; reports that as an error on every startup thereafter.
Type: files; Name: "{#AddinsDir}\{#ManifestName}"

[Code]

// The assembly path in a Revit manifest has to be absolute, and where it lands
// is not known until the person installing has chosen. So the manifest is
// shipped with the path left as a placeholder and finished here.
//
// The template is generated by the build script, which strips the developer
// commentary out of it first. Doing that here would mean writing a comment
// stripper in Pascal; doing it there means the committed template stays the
// one source of truth for what Revit is told.
function WriteManifest(): Boolean;
var
  Template: AnsiString;
  Manifest: string;
  Folder: string;
begin
  Result := False;

  if not LoadStringFromFile(ExpandConstant('{app}\{#ManifestName}.in'), Template) then
  begin
    MsgBox('The add-in manifest template could not be read, so Revit has not been told about the add-in.',
           mbError, MB_OK);
    Exit;
  end;

  Manifest := String(Template);
  StringChangeEx(Manifest, '{ASSEMBLY_PATH}', ExpandConstant('{app}\SpatialAnalyzer.Revit.dll'), True);

  if Pos('{ASSEMBLY_PATH}', Manifest) > 0 then
  begin
    MsgBox('The add-in manifest still contains its placeholder, so Revit has not been told about the add-in.',
           mbError, MB_OK);
    Exit;
  end;

  Folder := ExpandConstant('{#AddinsDir}');
  if not ForceDirectories(Folder) then
  begin
    MsgBox('Revit''s add-ins folder could not be created:' + #13#10 + Folder, mbError, MB_OK);
    Exit;
  end;

  // UTF-8 without a byte order mark: the manifest declares encoding="utf-8"
  // and Revit's parser is happier without a mark in front of the declaration.
  Result := SaveStringToFile(Folder + '\{#ManifestName}', Manifest, False);

  if not Result then
    MsgBox('The add-in manifest could not be written to:' + #13#10 + Folder, mbError, MB_OK);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    WriteManifest();
end;

// Said before anything is installed rather than discovered afterwards. The
// add-in is built against Revit 2025 and will not load into another version,
// so installing it where there is no Revit 2025 achieves nothing - but it is
// a warning and not a refusal, because installing before Revit is a reasonable
// order to do things in.
function InitializeSetup(): Boolean;
begin
  Result := True;

  if not DirExists(ExpandConstant('{commonpf}\Autodesk\Revit {#RevitVersion}')) then
    Result := MsgBox('Revit {#RevitVersion} was not found on this computer.' + #13#10 + #13#10 +
                     'This add-in is built for Revit {#RevitVersion} and will not load into any other ' +
                     'version. Install it anyway?', mbConfirmation, MB_YESNO) = IDYES;
end;
